- .travis.yml
Updating travis ci dist to xenial (instead of trusty). Trusty does not use cmake 3, and is about to be retired.
> Updating Travis ci dist to xenial (instead of trusty)

- CMakeLists.txt
- cmake/Modules/UseDoxygen.cmake
Just some changes to make use of CMake 3.1 features
- Enforce the minimum CMake version, and set 3.14 as max tested (as it's what I'm using)
(Using CMake > 3.14 won't fail, instead it'll automatically set compatibility options for new 3.14+ features)
- Update Doxygen module, as (implicitly) removing 2.x compatibility options breaks it
- Configure for C++11 standard in the recommended CMake manner
- Bring the CMake generation-process output a little more in line with libopenshot's
> Cmake 3.1+ project updates

- CMakeLists.txt
Without this line, builds fail on Linux and Mac
> Add ENABLE_LANGUAGE(C) to CMakeList

- .travis.yml
As in OpenShot/libopenshot#223, run the install step after build (with `DESTDIR=dist/`) to exercise more of the build tooling.
> Travis CI: Also run `make install`

- CMakeLists.txt
- Doxyfile.in
- INSTALL.md
- cmake/Modules/UseDoxygen.cmake
- doc/INSTALL-LINUX.md
- doc/INSTALL-MAC.md
- doc/INSTALL-WINDOWS.md
- doc/process_source_files.py
Doxygen was having real trouble generating clean docs from the JUCE sources, but their own website docs were generated with Doxygen as well, and looked great.
Turns out, they preprocess their own source files before generating docs from them. Borrowed their Python script to munge the sources, made a few changes, and connected it up as a new target dependency for `make doc`. It'll only run if the docs are requested to be built, and `make clean` will clear out the preprocessed sources if it's run.
After incorporating some of their Doxyfile settings into ours, and importing the fixes to our files that I'd already made over @ OpenShot/libopenshot#245, the docs still don't come out _perfect_, but they're about as close as we can hope for, and almost readable!
> Upgrade Doxygen docs

- CMakeLists.txt
CMake will now discover for Python 3 in addition to Doxygen, as a
prerequisite for creating a `doc` target. If everything checks out,
the user can run `make doc` to generate formatted docs, and they
will be installed to `${CMAKE_INSTALL_DOCDIR}` (typically
`${CMAKE_INSTALL_PREFIX}/share/doc/libopenshot/audio/`) when
`make install` is run.
> Fix Python3 discovery, add docs install

- .gitlab-ci.yml
Moving 64-bit and 32-bit Windows builders to AWS, and updating all dependencies and build tools. `MinGW Makefiles` is no longer working, and it appears things have changed to `MSYS Makefiles` now. FYI: This will speed up our Windows builds quite a bit! (libopenshot-audio)
> Updating MSYS2, New Cmake builder syntax

- .gitlab-ci.yml
Not sure if this is really the issue I've been battling on our 32-bit Windows builds, but I'm hoping this resolves some problems downstream... related to crashes on older versions of 32-bit windows.
> Enable 32-bit Windows builds of libopenshot-audio

- CMakeLists.txt
Fixing order of windows link commands (hopefully). Kernel32.dll must come after Winmm.dll, or older versions of 32-bit windows will fail to find certain symbols. Newer versions of Kernel32.dll have symbols which also appear in winmm.dll. However, on older versions of 32-bit Windows, those symbols are not found in kernel32.dll, and will thus, fail.
> Kernel32.dll must come after Winmm.dll (or else)

- CMakeLists.txt
@jonoomph 
So... check this out... (!!)
It _links_ cleanly, at least. And `openshot-audio-test-sound` plays. On my Win7 64-bit VM.
No worries about kernel32 causing troubles, either, since it's not there!
> Prune Win32 link libraries

- .travis.yml
This adds a MacOS build (`os: osx`) to the Travis build matrix, alongside the existing Linux build. Each build will be carried out on both platforms simultaneously.
It also:
- Uses Travis' apt addon to install packages, rather than `sudo apt-get`
(MacOS packages are installed using `brew install` commands)
- No longer installs the libopenshot-audio PPA or the libopenshot-audio-dev package prior to building the source tree
- Installs doxygen (and graphviz on Linux)
- Runs `make doc` before `make install`
- Uses `CMAKE_INSTALL_PREFIX` instead of `make DESTDIR`
> Travis: add MacOS building

- .gitignore
I tend to create multiple build paths at the root of the project, for testing various configurations. So I'll  have all of `build/`, `build-somebranch/`, `build-otherbranch/`, etc. sitting around. The current `.gitignore` will only ignore a directory named exactly `build`.
This PR updates the `.gitignore` for the repo to exclude `/build*`, meaning _anything_ with a name that starts with `build`, if it's located at the root of the repository tree.
> gitignore: Exclude all build* files/directories @ root level

- CMakeLists.txt
This moves the installation target directory for the documentation files to `${CMAKE_INSTALL_DOCDIR}/API`, which on most systems is `${CMAKE_INSTALL_PREFIX}/share/doc/libopenshot-audio/API`. 
(The API docs are hundreds of HTML files, so I figured it was better to keep them contained in a subdir. They were previously all being dumped into `${CMAKE_INSTALL_PREFIX}/share/doc/libopenshot-audio/`)
> Change installation directory for docs to DOCDIR/API

- .travis.yml
- src/Main.cpp
This corrects the only remaining warning in GCC (an unused variable in the test program code), and updates the Travis command line with `-DCMAKE_CXX_FLAGS_DEBUG="-Wall -Wpedantic"` to enable warnings if anything is amiss in the code.
(`-Wextra`, the other common set of GCC warnings, unfortunately produces a lot of false positives in the JUCE code, so it's omitted for now.)
> Build the wall

- .travis.yml
This adds a third build environment, Ubuntu 18.04, alongside the existing 16.04 and macOS builds. (IMHO we can probably drop 16.04 once we've got this shaken out, but for now they'll be run side-by-side.)
> Travis: Add Ubuntu Bionic (18.04) builds

- CMakeLists.txt
Like previous PRs, this switches to using the `IMPORTED` target `Thread::Thread` to use `pthread` with libopenshot-audio. It also adopts CMake's recommended configuration. (`THREADS_PREFER_PTHREAD_FLAG` set to true, causing the `-pthread` flag to be passed to the compiler and linker, rather than the library being symlinked "manually".)
Tested with CMake 3.1 and 3.14.
> Use IMPORTED target and update configs for Thread library

- CMakeLists.txt
Since CMake 3.1 (our minimum supported version), `FindZLIB.cmake` creates the `IMPORTED` target `ZLIB::ZLIB` to encapsulate its dependencies. Use that to properly link the library and include dirs on all three platforms.
> ZLIB: Use IMPORTED target for linking

- CMakeLists.txt
As with the previous PR, this links libopenshot-audio with the `IMPORTED` target `ALSA::ALSA`, rather than the associated variables.
However, since CMake prior to 3.12 didn't create the `ALSA::ALSA` target, for backwards compatibility we create it ourselves. Tested with both CMake 3.1 and 3.14.
> ALSA: Use or create IMPORTED library target

- .travis.yml
The `.travis.yml` file is installing SWIG and UnitTest++ on both Linux and MacOS, which makes no sense because neither is needed to build libopenshot-audio.
> Travis: Remove unused packages

- JuceLibraryCode/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp
This is a cherry-pick of [this commit](https://github.com/WeAreROLI/JUCE/commit/8a66f1f3d3750b9ecdf909821dd4b144511b00a2) from the JUCE source  tree, which is reported to fix the input-device mismatch issue OpenShot users have been reporting. This is meant as a stopgap measure until the JUCE 5.4.5 upgrade can be merged (#77).
Fixes OpenShot/openshot-qt#3073, fixes OpenShot/openshot-qt#2957
> Apply JUCE input device fix

- src/Main.cpp
This PR makes some changes to the `src/Main.cpp` file:
- Convert from Windows CRLF line-endings to Unix CR, and clean up some tab-spacing
- Eliminate `using namespace std;` by adding `std::` prefixes
- Eliminate the hackery of platform-specific `sleep()` implementations by using `juce::Thread::sleep()`, which is supported cross-platform
> Some fixes to Main.cpp: line endings, std:: prefixes, use juce::Thread::sleep()

- .travis.yml
Most of our build time is taken up by the MacOS build, and most of _that_ time is spent updating Homebrew packages we don't actually need or use.
So, this is an experiment with using a config that includes `homebrew: update: false`. I _think_ I tried that originally, and it caused some sort of problems with the installs not working... but I can't remember for sure, and if it's possible to save all that time per build, it's worth attempting.
> Travis: Remove homebrew

- CMakeLists.txt
- src/hex_version.cpp
Use a C++ program (built and run by CMake when generating the build) to convert the dotted-decimal project version into a hexadecimal number instead of hardcoding it, for CMake < 3.13.
> CMake: Add hex-version helper source

- .github/stale.yml
Experimental support for `stale` plugin, to help with issue management on GitHub.  https://github.com/marketplace/stale
Related PR for libopenshot: https://github.com/OpenShot/libopenshot/pull/460
> Adding stale bot for github issue management (libopenshot-audio)

- .travis.yml
It looks like some of the APIs being used in our current JUCE code are deprecated, as XCode calls out when building with a recent version. Add such a build to Travis, so we can keep an eye on that.
> Travis: Add macOS build w/ newer XCode

- version.sh
This adds a `version.sh` script that uses grep and sed to extract the `PROJECT_FULL_VERSION` string from the `CMakeLists.txt` file. (Hopefully we'll all remember to update it if we change the format at any point.)
This is useful for building libopenshot-audio as a Mac Homebrew `brew diy` project, which allows ad-hoc building of packages that install directly into the Homebrew environment.
e.g.
```sh
$ cd libopenshot-audio
$ cmake $(brew diy --name libopenshot-audio --version $(sh ./version.sh)) .
[CMake runs with CMAKE_INSTALL_PREFIX set to $(brew --cellar)/libopenshot-audio/<version>/]
$ cmake --build .
$ cmake --build . --target install
$ brew link libopenshot-audio
```
...and libopenshot-audio is linked into `/usr/local/opt/{lib,include}`.
> Add shell script to output version

- CMakeLists.txt
- JuceLibraryCode/modules/juce_core/maths/juce_MathsFunctions.h
(See [Debian bug 925755](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925755) for background.)
Debian have a distro package `juce-modules-source` that they can build against, but they need to be able to point us there. This PR adds a `JUCE_MODULES_PATH` cache variable, default to `${CMAKE_CURRENT_BINARY_DIR}/JuceLibraryCode/modules`, that can be overridden at build system generation time via:
```sh
cmake -DJUCE_MODULES_PATH=/usr/share/juce/modules
```
Tha'll allow Debian to build against their version of JUCE, instead of our bundled one.
I also reverted the old `isfinite()` fix patch, so that we're using an _unpatched_ version of JUCE, since they'll be doing the same. I figured out how to fix the `isfinite()` thing from the libopenshot build configs end, and a corresponding PR there …
> Add JUCE_MODULES_PATH config variable

- .gitlab-ci.yml
Changes GitLab builder to new Linux builder, and removes libstdc++ dependency from libopenshot-audio. 
Related to PRs:
https://github.com/OpenShot/libopenshot/pull/549
https://github.com/OpenShot/openshot-qt/pull/3604
> Small tweaks to GitLab and clang support (removing libstdc++ dependency on Mac)

- .travis.yml
- CMakeLists.txt
This PR adds a fifth CI build, using Ubuntu's latest LTS release.
I'm tempted to drop Xenial _off_ the list (four builds seems like plenty), but maybe instead I'll switch one of the Ubuntu builds over to Clang or something like that. Might as well make themselves useful.
> Travis: Add Focal build

- .github/stale.yml
Fixing YML string for Stale plugin so it doesn't mess up our string formatting (instead of folded style, use a literal string)
> Fix string formatting on yml stale message 

- .github/workflows/ci.yml
`setup-msys2` in the CI workflow is installing all of `mingw-w64-x86_64-toolchain` and `base-devel` which is **way** too many packages we don't need or use. Trying to pare it down to just the minimum required to build libopenshot-audio.
> CI: Pare down Windows deps

- .gitlab-ci.yml
Adding `make` threads to libopenshot-audio and libopenshot, to increase speed of compilation. Related to https://github.com/OpenShot/libopenshot/pull/632.
Speed comparisons:
- libopenshot-audio(linux): 33 seconds -> 28 seconds (a bit faster)
- libopenshot-audio (mac): 55 seconds -> 30 seconds (almost twice as fast)
> Experimental multi-thread builds for Linux and Mac

- src/CMakeLists.txt
If the CMake version is old enough (like on Ubuntu's build servers), the C++11 standard level and other compile configuration won't be transitive from the library. (It is, in all recent CMake releases.)
> Ensure we use C++11 to build demo code

- src/CMakeLists.txt
The Ubuntu PPA packaging doesn't include the `openshot-audio-demo` binary, because why would it?
But, turns out if it's _not_ installed, then having it in the target file causes CMake to abort with a missing-file error. So, better not to include it in the EXPORTED configuration at all.
> CMake: Don't export openshot-audio-demo

- .github/workflows/main.yml
Just like we've been doing in OpenShot/openshot-qt for a while now, this adds a Github Actions workflow to generate the repo's documentation, then publish it as a downloadable build artifact.
> GH Actions: Build and publish docs

- CMakeLists.txt
- include/JuceHeader.h.in
My recent #118 changed the name of the primary header from `JuceHeader.h` to `OpenShotAudio.h`, but also installed that file as a link/copy under the name `JuceHeader.h` for backwards compatibility.
Turns out, that's a problem if you happen to mix both `#include` forms in the same project, because you'll end up with errors about symbols being redefined or duplicated. So, this PR replaces the copy/link to `JuceHeader.h` with a new stub file that contains only two business lines:
```c++
#pragma once
#include "./OpenShotAudio.h"
```
That way, nothing breaks if both files are `#included` together.
> Fix legacy JuceHeader.h

- CMakeLists.txt
I was steered wrong, and set up the `OpenShotAudioConfig.cmake` file (and friends) to install to `share/cmake/`... that path is OK for arch-independent installs, but _not_ for architecture-bound library installs like `libopenshot-audio`. Those should go into the same `${CMAKE_INSTALL_LIBDIR}` that the libraries themselves go into, so that a multi-arch system can simultaneously have, e.g.:
* `/usr/lib/cmake/OpenShotAudio/OpenShotAudioConfig.cmake` pointing to a 32-bit version
* `/usr/lib64/xmake/OpenShotAudio/OpenShotAudioConfig.cmake` pointing to a 64-bit version
...and the right one will be used automatically.
Looking to merge this as soon as the CI is ready, because it has to be coordinated with a corresponding change to the Ubuntu PPA packaging control files (as they expect files to be …
> CMake: Correct EXPORTED config install path

- CMakeLists.txt
Because `@NEED_ASIO@` is substituted in generating the CMake `Config.cmake` file, it should always have a value of either `TRUE` or `FALSE`. This PR ensures that it defaults to `FALSE`.
> Ensure NEED_ASIO is always set
